$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: telco-churn-env
version: 1
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

conda_file: environment.yml
