name: churn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - scikit-learn>=1.3.0
      - pandas>=2.0.0
      - numpy>=1.24.0
      - mlflow==2.3.1
      - azure-ai-ml>=1.19.0
      - azure-identity>=1.16.0
      - python-dotenv>=1.0.0
      - joblib>=1.3.0
