$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: telco-cust-churn-model-deploy
endpoint_name: telco-customer-churn-endpoint

model: azureml:telco-customerchurn-model:1  

environment: azureml:telco-customer-churn-env3:4

code_configuration:
  code: ../src
  scoring_script: score.py

instance_type: Standard_D2as_v4
instance_count: 1
